name: CI

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Initialize
        run: |
          apt-get update
          apt-get install -y curl jq
      - name: Release version
        run: |
          set -e
          echo "TRAEFIK_VERSION=$(curl -s https://api.github.com/repos/traefik/traefik/tags | jq -r '.[] | select(contains({name: "rc"})|not)' | jq -sr '.[0].name' | sed -e 's/v//')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config push.default current
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Push Tag
        run: |
          set -e
          sed -i -e "s/^ENV TRAEFIK_VERSION .*$/ENV TRAEFIK_VERSION $TRAEFIK_VERSION/" Dockerfile
          sed -i -e "/^# traefik Version$/{n;d;}" README.md
          sed -i -e "/^# traefik Version$/a $TRAEFIK_VERSION" README.md
          git add README.md
          git add Dockerfile
          set +e
          git commit -m "Bump version $TRAEFIK_VERSION from GitHub Actions"
          set -e
          git push origin
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ env.TRAEFIK_VERSION }}
          release_name: Release ${{ env.TRAEFIK_VERSION}}
          draft: false
          prerelease: false
